package:
  name: rosettax
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  git_url: https://github.com/MartinPdeS/RosettaX.git

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

channels:
  - conda-forge
  - martinpdes

requirements:
  host:
    - python >=3.8
    - setuptools >=40.8.0
    - wheel
    - setuptools-scm >=8.0
    - pip
    - martinpdes::mpsplots
  run:
    - numpy
    - pydantic
    - martinpdes::pymiesim
    - martinpdes::mpsplots


about:
  home: https://github.com/MartinPdeS/RosettaX
  license: MIT
  summary: "A package for refractive index values."
  description: PyOptik is a library that helps the end-user to build it's own refractive index library.
  dev_url: https://github.com/MartinPdeS/RosettaX
  doc_url: https://rosettax.readthedocs.io
  license_file: LICENSE
  keywords:
    - flow-cytometre
    - calibration
    - physics
    - data-analysis

test:
  imports:
    - RosettaX
  requires:
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ~=1.5
    - coverage ~=7.6
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS